version: '3.8'

services:
  solid-pod-demo:
    build:
      args:
        NODE_ENV: development
    image: solid-pod-demo-development
    container_name: solid-pod-demo-development
    ports:
      - "1234:1234"
      - "9229:9229"
    volumes:
      - ./src/:/home/node/app/src/
      - ./package.json:/home/node/app/package.json
