version: '3.8'

services:
  solid-pod-demo:
    build:
      args:
        NODE_ENV: development
    image: solid-pod-demo-development
    container_name: solid-pod-demo-development
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./:/home/node/app
